version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./backend:/app
    command: mvn spring-boot:run
    working_dir: /app

  frontend:
    image: node:16-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: sh -c "cd /app && npm install && npm start"
    working_dir: /app
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api